# TODO Setup auth - https://docs.docker.com/registry/deploying/#restricting-access
version: "3.9"
services:
  registry-one:
    image: "registry:2"
    ports:
      - 5001:5000
    # https://github.com/containers/skopeo/issues/463
    # More options https://docs.docker.com/registry/configuration/
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    volumes:
      - ./registry/one/data:/var/lib/registry
  registry-two:
    image: "registry:2"
    ports:
      - 5002:5000
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    volumes:
      - ./registry/two/data:/var/lib/registry